# Generated by Django 3.1.7 on 2021-05-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDailyBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalKeyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change', models.FloatField()),
                ('change_ratio', models.FloatField()),
                ('market_value', models.FloatField()),
                ('volume', models.FloatField()),
                ('turnover_rate', models.FloatField()),
                ('vibrate_ratio', models.FloatField()),
                ('avg_vol_10d', models.FloatField()),
                ('avg_vol_3m', models.FloatField()),
                ('pe', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('pe_ttm', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('eps_ttm', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('ps', models.FloatField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True, null=True)),
                ('short_float', models.FloatField(blank=True, null=True)),
                ('total_shares', models.FloatField()),
                ('outstanding_shares', models.FloatField()),
                ('fifty_two_wk_high', models.FloatField()),
                ('fifty_two_wk_low', models.FloatField()),
                ('latest_earnings_date', models.CharField(max_length=128)),
                ('estimate_earnings_date', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMinuteBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('vwap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TradingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.BooleanField(default=True)),
                ('order_amount_limit', models.FloatField()),
                ('min_surge_amount', models.FloatField()),
                ('min_surge_volume', models.FloatField()),
                ('min_surge_change_ratio', models.FloatField()),
                ('observe_timeout_in_sec', models.IntegerField()),
                ('pending_order_timeout_in_sec', models.IntegerField()),
                ('holding_order_timeout_in_sec', models.IntegerField()),
                ('max_bid_ask_gap_ratio', models.FloatField()),
                ('target_profit_ratio', models.FloatField()),
                ('stop_loss_ratio', models.FloatField()),
                ('refresh_login_interval_in_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebullCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cred', models.TextField(blank=True, null=True)),
                ('paper', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebullNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('source_name', models.CharField(max_length=64)),
                ('collect_source', models.CharField(max_length=64)),
                ('news_time', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('news_url', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WebullOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('ticker_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=64)),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'BUY'), (1, 'SELL')], default=0)),
                ('status', models.CharField(max_length=64)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('filled_quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('filled_time', models.DateTimeField(blank=True, null=True)),
                ('placed_time', models.DateTimeField(blank=True, null=True)),
                ('time_in_force', models.PositiveSmallIntegerField(choices=[(0, 'GTC'), (1, 'DAY'), (2, 'IOC')], default=0)),
                ('paper', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebullOrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
