# Generated by Django 3.1.7 on 2021-05-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebullAccountStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_liquidation', models.FloatField()),
                ('total_profit_loss', models.FloatField()),
                ('total_profit_loss_rate', models.FloatField()),
                ('day_profit_loss', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
