# Generated by Django 3.1.7 on 2021-05-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0002_webullaccountstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='trade_interval_in_sec',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
