# Generated by Django 3.1.7 on 2021-05-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0002_tradingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='bps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='eps_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='forward_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='pb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='pe_ttm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='ps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
