# Generated by Django 3.1.7 on 2021-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0003_tradingsettings_trade_interval_in_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='webullorder',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'LMT'), (1, 'MKT'), (2, 'STP'), (3, 'STP LMT'), (4, 'STP TRAIL')], default=0),
        ),
    ]
