# Generated by Django 3.1.7 on 2021-05-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0003_auto_20210502_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webullnews',
            old_name='trade_date',
            new_name='date',
        ),
    ]
