# Generated by Django 3.1.7 on 2021-05-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0004_webullorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webullordernote',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '(Day) First candle new high'), (1, '(Day) Gap and Go'), (2, '(Day) Bull Flag'), (3, '(Day) Reversal'), (4, '(Swing) 20 days new high')], default=0),
        ),
    ]
