# Generated by Django 3.1.7 on 2021-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0004_auto_20210502_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webullnews',
            old_name='source',
            new_name='collect_source',
        ),
        migrations.AddField(
            model_name='webullnews',
            name='source_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
