# Generated by Django 3.1.7 on 2021-05-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0005_auto_20210502_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkeystatistics',
            name='short_float',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
