# Generated by Django 3.1.7 on 2021-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0006_historicaldaytradeperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default - Trade as much as possible, mainly for gather data.'), (1, 'Dynamic Optimize - Trade based on win rate, reduce size if win rate is low.')], default=0),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='blacklist_timeout_in_sec',
            field=models.IntegerField(default=1800),
            preserve_default=False,
        ),
    ]
