# Generated by Django 3.1.7 on 2021-05-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0006_historicalkeystatistics_short_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='short_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
