# Generated by Django 3.1.7 on 2021-05-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_ross', '0007_auto_20210511_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default - Trade as much as possible, mainly for collect data.'), (1, 'Dynamic Optimize - Trade based on win rate, reduce size if win rate is low.')], default=0),
        ),
    ]
