# Generated by Django 3.1.7 on 2021-05-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTopGainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('ticker_id', models.CharField(max_length=128)),
                ('change', models.FloatField()),
                ('change_percentage', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTopLoser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('ticker_id', models.CharField(max_length=128)),
                ('change', models.FloatField()),
                ('change_percentage', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
