# Generated by Django 3.1.7 on 2021-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0002_historicaltopgainer_historicaltoploser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='avg_confirm_volume',
            field=models.FloatField(default=6000),
            preserve_default=False,
        ),
    ]
