# Generated by Django 3.1.7 on 2021-05-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0003_tradingsettings_avg_confirm_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('screener_type', models.PositiveSmallIntegerField(choices=[(0, 'Manual'), (1, 'Earning Day'), (2, 'Unusual Volume'), (3, 'Channel Up'), (4, 'Double Bottom')], default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '[DAY/MOMO] Momo day trade as much as possible, mainly for collect data.'), (1, '[DAY/MOMO (REDUCE SIZE)] Momo day trade based on win rate, reduce size when win rate low.'), (3, '[DAY/MOMO (NEW HIGH)] Momo day trade, no entry if the price not break max of last high price.'), (2, '[DAY/RED GREEN] Day trade based on red to green strategy.'), (100, '[SWING/TURTLE (20 DAYS)] Swing trade based on turtle trading rules (20 days).'), (101, '[SWING/TURTLE (55 DAYS)] Swing trade based on turtle trading rules (55 days).'), (200, '[LIVE] Live day/swing trade based on history statistics data.')], default=0),
        ),
        migrations.AlterField(
            model_name='webullordernote',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high')], default=0),
        ),
    ]
