# Generated by Django 3.1.7 on 2021-05-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0004_auto_20210527_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=64)),
                ('cost', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('buy_date', models.DateField()),
                ('buy_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SwingTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('buy_date', models.DateField()),
                ('buy_time', models.DateTimeField()),
                ('buy_price', models.FloatField()),
                ('buy_order_id', models.CharField(max_length=128)),
                ('sell_date', models.DateField()),
                ('sell_time', models.DateTimeField()),
                ('sell_price', models.FloatField()),
                ('sell_order_id', models.CharField(max_length=128)),
                ('setup', models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high')], default=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='swingwatchlist',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
