# Generated by Django 3.1.7 on 2021-05-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0005_auto_20210527_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='outstanding_shares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='total_shares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='turnover_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='vibrate_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
