# Generated by Django 3.1.7 on 2021-05-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0007_tradinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinglog',
            name='tag',
            field=models.CharField(default='DayTradingMomo', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '[DAY/MOMO] Momo day trade as much as possible, mainly for collect data.'), (1, '[DAY/MOMO (REDUCE SIZE)] Momo day trade based on win rate, reduce size when win rate low.'), (3, '[DAY/MOMO (NEW HIGH)] Momo day trade, no entry if the price not break max of last high price.'), (2, '[DAY/RED GREEN] Day trade based on red to green strategy.'), (100, '[SWING/TURTLE (20 DAYS)] Swing trade based on turtle trading rules (20 days).'), (101, '[SWING/TURTLE (55 DAYS)] Swing trade based on turtle trading rules (55 days).'), (200, '[DAY/SWING] Day/Swing trade based on history statistics data.')], default=0),
        ),
    ]
