# Generated by Django 3.1.7 on 2021-05-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0009_auto_20210528_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='swing_position_amount_limit',
            field=models.FloatField(default=2000.0),
            preserve_default=False,
        ),
    ]
