# Generated by Django 3.1.7 on 2021-05-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0013_auto_20210531_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvernightPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=64)),
                ('ticker_id', models.CharField(max_length=128)),
                ('cost', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('buy_date', models.DateField()),
                ('buy_time', models.DateTimeField()),
                ('setup', models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (5, '[Day] 20 minutes new high'), (6, '[Day] Earning Gap'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high')], default=6)),
            ],
        ),
        migrations.CreateModel(
            name='OvernightTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('buy_date', models.DateField()),
                ('buy_time', models.DateTimeField()),
                ('buy_price', models.FloatField()),
                ('buy_order_id', models.CharField(max_length=128)),
                ('sell_date', models.DateField()),
                ('sell_time', models.DateTimeField()),
                ('sell_price', models.FloatField()),
                ('sell_order_id', models.CharField(max_length=128)),
                ('setup', models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (5, '[Day] 20 minutes new high'), (6, '[Day] Earning Gap'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high')], default=6)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='swingposition',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (5, '[Day] 20 minutes new high'), (6, '[Day] Earning Gap'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high')], default=100),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='max_prev_day_close_gap_ratio',
            field=models.FloatField(default=0.02),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='min_earning_gap_ratio',
            field=models.FloatField(default=0.04),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='min_relative_volume',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
