# Generated by Django 3.1.7 on 2021-06-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0014_auto_20210531_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='day_trade_usable_cash_threshold',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '[DAY (MOMO)] Momo day trade as much as possible, mainly for collect data.'), (1, '[DAY (MOMO REDUCE SIZE)] Momo day trade based on win rate, reduce size when win rate low.'), (3, '[DAY (MOMO NEW HIGH)] Momo day trade, no entry if the price not break max of last high price.'), (2, '[DAY (RED GREEN)] Day trade based on red to green strategy.'), (4, '[DAY (BREAKOUT)] Breakout day trade, entry if price reach 20 minutes new high.'), (5, '[DAY (EARNING)] Earning date day trade, entry if gap up.'), (100, '[SWING (TURTLE 20)] Swing trade based on turtle trading rules (20 days).'), (101, '[SWING (TURTLE 55)] Swing trade based on turtle trading rules (55 days).'), (201, '[DAY/SWING (R-G/TURTLE)] Day/Swing trade with red to green and turtle (55 days) strategy.'), (202, '[DAY/SWING (BREAKOUT/TURTLE)] Day/Swing trade with breakout (20 minutes) and turtle (55 days) strategy.')], default=0),
        ),
    ]
