# Generated by Django 3.1.7 on 2021-06-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0016_auto_20210603_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '[DAY (MOMO)] Momo day trade as much as possible, mainly for collect data.'), (1, '[DAY (MOMO REDUCE SIZE)] Momo day trade based on win rate, reduce size when win rate low.'), (3, '[DAY (MOMO NEW HIGH)] Momo day trade, no entry if the price not break max of last high price.'), (2, '[DAY (RED GREEN)] Day trade based on red to green strategy.'), (4, '[DAY (BREAKOUT)] Breakout day trade, entry if price reach 20 minutes new high.'), (5, '[DAY (EARNINGS)] Earning date day trade, entry if gap up.'), (100, '[SWING (TURTLE 20)] Swing trade based on turtle trading rules (20 days).'), (101, '[SWING (TURTLE 55)] Swing trade based on turtle trading rules (55 days).'), (201, '[DAY (R-G) / SWING (TURTLE)] Day/Swing trade with red to green / turtle (55 days) strategy.'), (202, '[DAY (BREAKOUT) / SWING (TURTLE)] Day/Swing trade with breakout (20 minutes) / turtle (55 days) strategy.'), (203, '[DAY (EARNINGS) / SWING (TURTLE)] Day/Swing trade with earning gap up / turtle (55 days) strategy.')], default=0),
        ),
    ]
