# Generated by Django 3.1.7 on 2021-06-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0017_auto_20210603_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='swingwatchlist',
            name='exchange',
            field=models.CharField(default='NASDAQ', max_length=64),
        ),
        migrations.AddField(
            model_name='swingwatchlist',
            name='is_etf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swingwatchlist',
            name='sector',
            field=models.CharField(default='Technology', max_length=64),
        ),
        migrations.AddField(
            model_name='swingwatchlist',
            name='units',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '[DAY (MOMO)] Momo day trade as much as possible, mainly for collect data.'), (1, '[DAY (MOMO REDUCE SIZE)] Momo day trade based on win rate, reduce size when win rate low.'), (3, '[DAY (MOMO NEW HIGH)] Momo day trade, no entry if the price not break max of last high price.'), (2, '[DAY (RED GREEN)] Day trade based on red to green strategy.'), (4, '[DAY (BREAKOUT)] Breakout day trade, entry if price reach 20 minutes new high.'), (5, '[DAY (EARNINGS)] Earning date day trade, entry if gap up and exit trade intraday.'), (6, '[DAY (EARNINGS OVERNIGHT)] Earning date day trade, entry if gap up and may hold position overnight.'), (7, '[DAY (EARNINGS BREAKOUT)] Earning date day trade, entry if gap up and do breakout trade if no earning event.'), (100, '[SWING (TURTLE 20)] Swing trade based on turtle trading rules (20 days).'), (101, '[SWING (TURTLE 55)] Swing trade based on turtle trading rules (55 days).'), (201, '[DAY (RED GREEN) / SWING (TURTLE 55)] Day trade based on red to green strategy. / Swing trade based on turtle trading rules (55 days).'), (202, '[DAY (BREAKOUT) / SWING (TURTLE 55)] Breakout day trade, entry if price reach 20 minutes new high. / Swing trade based on turtle trading rules (55 days).'), (203, '[DAY (EARNINGS) / SWING (TURTLE 55)] Earning date day trade, entry if gap up and exit trade intraday. / Swing trade based on turtle trading rules (55 days).')], default=0),
        ),
    ]
