# Generated by Django 3.1.7 on 2021-06-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0022_auto_20210613_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='webullcredentials',
            name='trade_pwd',
            field=models.CharField(default='123456', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '[DAY (MOMO)] Momo day trade as much as possible, mainly for collect data.'), (1, '[DAY (MOMO REDUCE SIZE)] Momo day trade based on win rate, reduce size when win rate low.'), (3, '[DAY (MOMO NEW HIGH)] Momo day trade, no entry if the price not break max of last high trade price.'), (2, '[DAY (RED GREEN)] Day trade based on red to green strategy.'), (10, '[DAY (BREAKOUT 10)] Breakout day trade, entry if price reach 10 minutes new high.'), (4, '[DAY (BREAKOUT 20)] Breakout day trade, entry if price reach 20 minutes new high.'), (5, '[DAY (BREAKOUT 30)] Breakout day trade, entry if price reach 30 minutes new high.'), (6, '[DAY (BREAKOUT EARNINGS)] Breakout and earning day trade, entry if price reach 30 minutes new high.'), (11, '[DAY (BREAKOUT NEW HIGH)] Breakout day trade, no entry if the price not break max of last high trade price.'), (
                7, '[DAY (EARNINGS)] Earning date day trade, entry if gap up and exit trade intraday.'), (8, '[DAY (EARNINGS OVERNIGHT)] Earning date day trade, entry if gap up and may hold position overnight.'), (9, '[DAY (EARNINGS BREAKOUT)] Earning date day trade, entry if gap up and do breakout trade if no earning event.'), (100, '[SWING (TURTLE 20)] Swing trade based on turtle trading rules (20 days).'), (101, '[SWING (TURTLE 55)] Swing trade based on turtle trading rules (55 days).'), (201, '[DAY (RED GREEN) / SWING (TURTLE 55)] Day trade based on red to green strategy. / Swing trade based on turtle trading rules (55 days).'), (202, '[DAY (BREAKOUT 10) / SWING (TURTLE 55)] Breakout day trade, entry if price reach 10 minutes new high. / Swing trade based on turtle trading rules (55 days).'), (203, '[DAY (EARNINGS) / SWING (TURTLE 55)] Earning date day trade, entry if gap up and exit trade intraday. / Swing trade based on turtle trading rules (55 days).')], default=0),
        ),
    ]
