# Generated by Django 3.1.7 on 2021-06-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0023_auto_20210617_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldaytradeperformance',
            name='total_buy_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldaytradeperformance',
            name='total_sell_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
