# Generated by Django 3.1.7 on 2021-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0024_auto_20210618_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTradeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'BUY'), (1, 'SELL')], default=0)),
                ('setup', models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (8, '[Day] 10 minutes new high'), (5, '[Day] 20 minutes new high'), (6, '[Day] 30 minutes new high'), (7, '[Day] Earning Gap'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high'), (500, '[Error] Failed to sell'), (999, 'Unknown')], default=100)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
