# Generated by Django 3.1.7 on 2021-07-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0027_auto_20210625_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingsettings',
            name='avg_confirm_amount',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='avg_confirm_volume',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='blacklist_timeout_in_sec',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='extended_avg_confirm_amount',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='extended_avg_confirm_volume',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='holding_order_timeout_in_sec',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='max_bid_ask_gap_ratio',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='max_prev_day_close_gap_ratio',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='min_earning_gap_ratio',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='min_relative_volume',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='min_surge_amount',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='min_surge_change_ratio',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='min_surge_volume',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='observe_timeout_in_sec',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='pending_order_timeout_in_sec',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='refresh_login_interval_in_min',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='trade_interval_in_sec',
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='day_free_float_limit_in_million',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='day_sectors_limit',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
