# Generated by Django 3.1.7 on 2021-07-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0031_auto_20210709_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquote',
            name='avg_price_200d',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockquote',
            name='avg_price_50d',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockquote',
            name='avg_volume',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
