# Generated by Django 3.1.7 on 2021-07-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0032_auto_20210713_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swingwatchlist',
            old_name='units',
            new_name='unit_weight',
        ),
        migrations.RemoveField(
            model_name='swingposition',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='swingposition',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='swingtrade',
            name='buy_order_id',
        ),
        migrations.RemoveField(
            model_name='swingtrade',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='swingtrade',
            name='sell_order_id',
        ),
        migrations.RemoveField(
            model_name='swingtrade',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='swingposition',
            name='add_unit_price',
            field=models.FloatField(default=9999),
        ),
        migrations.AddField(
            model_name='swingposition',
            name='order_ids',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swingposition',
            name='orders',
            field=models.ManyToManyField(to='webull_trader.WebullOrder'),
        ),
        migrations.AddField(
            model_name='swingposition',
            name='require_adjustment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='swingposition',
            name='stop_loss_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='swingposition',
            name='target_units',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='swingposition',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='swingposition',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swingtrade',
            name='order_ids',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swingtrade',
            name='orders',
            field=models.ManyToManyField(to='webull_trader.WebullOrder'),
        ),
        migrations.AddField(
            model_name='swingtrade',
            name='require_adjustment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='swingtrade',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='swingtrade',
            name='total_sold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='swingtrade',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
