# Generated by Django 3.1.7 on 2021-09-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0039_webullaccountstatistics_min_usable_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webullaccountstatistics',
            name='min_usable_cash',
            field=models.FloatField(default=0.0),
        ),
    ]
