# Generated by Django 3.1.7 on 2021-10-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0041_auto_20211003_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='day_turnover_rate_limit_percentage',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='day_free_float_limit_in_million',
            field=models.FloatField(default=-1.0),
        ),
    ]
