# Generated by Django 3.1.7 on 2021-10-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0042_auto_20211008_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebullOrderNote',
        ),
        migrations.AddField(
            model_name='webullorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayposition',
            name='add_unit_price',
            field=models.FloatField(default=99999.0),
        ),
        migrations.AlterField(
            model_name='swingposition',
            name='add_unit_price',
            field=models.FloatField(default=99999.0),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DAY (MOMO)'), (1, 'DAY (MOMO REDUCE SIZE)'), (3, 'DAY (MOMO NEW HIGH)'), (2, 'DAY (RED GREEN)'), (10, 'DAY (BREAKOUT 10)'), (4, 'DAY (BREAKOUT 20)'), (5, 'DAY (BREAKOUT 30)'), (6, 'DAY (BREAKOUT EARNINGS)'), (11, 'DAY (BREAKOUT NEW HIGH)'), (12, 'DAY (BREAKOUT 10-5)'), (13, 'DAY (BREAKOUT PRE LOSERS)'), (14, 'DAY (BREAKOUT 55)'), (7, 'DAY (EARNINGS)'), (8, 'DAY (EARNINGS OVERNIGHT)'), (9, 'DAY (EARNINGS BREAKOUT)'), (15, 'DAY (VWAP RECLAIM)'), (29, 'DAY (VWAP LARGE CAP)'), (16, 'DAY (GRINDING LARGE CAP)'), (17, 'DAY (GRINDING SYMBOLS)'), (18, 'DAY (BREAKOUT ASK)'), (19, 'DAY (BREAKOUT 20,11)'), (20, 'DAY (BREAKOUT 20,9)'), (21, 'DAY (BREAKOUT 20,8)'), (24, 'DAY (BREAKOUT 20,1)'), (22, 'DAY (BREAKOUT SCALE)'), (23, 'DAY (BREAKOUT PERIOD)'), (25, 'DAY (BREAKOUT DYN EXIT)'), (26, 'DAY (BREAKOUT SCALE MAX LOSS)'), (27, 'DAY (BREAKOUT SCALE ATR LOSS)'), (28, 'DAY (BREAKOUT SCALE PERIOD ROC)'), (100, 'SWING (TURTLE 20)'), (101, 'SWING (TURTLE 55)'), (201, 'DAY (RED GREEN) / SWING (TURTLE 55)'), (202, 'DAY (BREAKOUT 10) / SWING (TURTLE 55)'), (203, 'DAY (EARNINGS) / SWING (TURTLE 55)')], default=0),
        ),
    ]
