# Generated by Django 3.1.7 on 2021-10-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webull_trader', '0043_auto_20211023_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayposition',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (8, '[Day] 10 candles new high'), (5, '[Day] 20 candles new high'), (6, '[Day] 30 candles new high'), (7, '[Day] Earning Gap'), (9, '[Day] VWAP Reclaim'), (10, '[Day] Grinding Up'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high'), (500, '[Error] Failed to sell'), (999, 'Unknown')], default=5),
        ),
        migrations.AlterField(
            model_name='daytrade',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (8, '[Day] 10 candles new high'), (5, '[Day] 20 candles new high'), (6, '[Day] 30 candles new high'), (7, '[Day] Earning Gap'), (9, '[Day] VWAP Reclaim'), (10, '[Day] Grinding Up'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high'), (500, '[Error] Failed to sell'), (999, 'Unknown')], default=5),
        ),
        migrations.AlterField(
            model_name='historicaldailybar',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldailybar',
            name='symbol',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalkeystatistics',
            name='symbol',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalminutebar',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalminutebar',
            name='symbol',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalminutebar',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltopgainer',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltopgainer',
            name='symbol',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historicaltoploser',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltoploser',
            name='symbol',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='manualtraderequest',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (8, '[Day] 10 candles new high'), (5, '[Day] 20 candles new high'), (6, '[Day] 30 candles new high'), (7, '[Day] Earning Gap'), (9, '[Day] VWAP Reclaim'), (10, '[Day] Grinding Up'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high'), (500, '[Error] Failed to sell'), (999, 'Unknown')], default=100),
        ),
        migrations.AlterField(
            model_name='swinghistoricaldailybar',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='swinghistoricaldailybar',
            name='symbol',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='swingposition',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (8, '[Day] 10 candles new high'), (5, '[Day] 20 candles new high'), (6, '[Day] 30 candles new high'), (7, '[Day] Earning Gap'), (9, '[Day] VWAP Reclaim'), (10, '[Day] Grinding Up'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high'), (500, '[Error] Failed to sell'), (999, 'Unknown')], default=100),
        ),
        migrations.AlterField(
            model_name='swingtrade',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (8, '[Day] 10 candles new high'), (5, '[Day] 20 candles new high'), (6, '[Day] 30 candles new high'), (7, '[Day] Earning Gap'), (9, '[Day] VWAP Reclaim'), (10, '[Day] Grinding Up'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high'), (500, '[Error] Failed to sell'), (999, 'Unknown')], default=100),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='algo_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DAY (MOMO)'), (1, 'DAY (MOMO REDUCE SIZE)'), (30, 'DAY (MOMO SHARE SIZE)'), (3, 'DAY (MOMO NEW HIGH)'), (2, 'DAY (RED GREEN)'), (10, 'DAY (BREAKOUT 10)'), (4, 'DAY (BREAKOUT 20)'), (5, 'DAY (BREAKOUT 30)'), (6, 'DAY (BREAKOUT EARNINGS)'), (11, 'DAY (BREAKOUT NEW HIGH)'), (12, 'DAY (BREAKOUT 10-5)'), (13, 'DAY (BREAKOUT PRE LOSERS)'), (14, 'DAY (BREAKOUT 55)'), (7, 'DAY (EARNINGS)'), (8, 'DAY (EARNINGS OVERNIGHT)'), (9, 'DAY (EARNINGS BREAKOUT)'), (15, 'DAY (VWAP RECLAIM)'), (29, 'DAY (VWAP LARGE CAP)'), (16, 'DAY (GRINDING LARGE CAP)'), (17, 'DAY (GRINDING SYMBOLS)'), (18, 'DAY (BREAKOUT ASK)'), (19, 'DAY (BREAKOUT 20,11)'), (20, 'DAY (BREAKOUT 20,9)'), (21, 'DAY (BREAKOUT 20,8)'), (24, 'DAY (BREAKOUT 20,1)'), (22, 'DAY (BREAKOUT SCALE)'), (23, 'DAY (BREAKOUT PERIOD)'), (25, 'DAY (BREAKOUT DYN EXIT)'), (26, 'DAY (BREAKOUT SCALE MAX LOSS)'), (27, 'DAY (BREAKOUT SCALE ATR LOSS)'), (28, 'DAY (BREAKOUT SCALE PERIOD ROC)'), (100, 'SWING (TURTLE 20)'), (101, 'SWING (TURTLE 55)'), (201, 'DAY (RED GREEN) / SWING (TURTLE 55)'), (202, 'DAY (BREAKOUT 10) / SWING (TURTLE 55)'), (203, 'DAY (EARNINGS) / SWING (TURTLE 55)')], default=0),
        ),
        migrations.AlterField(
            model_name='webullorder',
            name='setup',
            field=models.PositiveSmallIntegerField(choices=[(0, '[Day] First candle new high'), (1, '[Day] Gap and Go'), (2, '[Day] Bull Flag'), (3, '[Day] Reversal'), (4, '[Day] Red to Green'), (8, '[Day] 10 candles new high'), (5, '[Day] 20 candles new high'), (6, '[Day] 30 candles new high'), (7, '[Day] Earning Gap'), (9, '[Day] VWAP Reclaim'), (10, '[Day] Grinding Up'), (100, '[Swing] 20 days new high'), (101, '[Swing] 55 days new high'), (500, '[Error] Failed to sell'), (999, 'Unknown')], default=999),
        ),
    ]
