WATCHLIST_SYMBOLS = [
    "AAPL", "ABNB", "AMZN", "AMD", "ASML", "AAL", "APHA", "ARRY", "ASAN",
    "ARKK", "ARKQ", "ARKW", "ARKG", "ARKF", "ARKX", "AQB", "API", "ALF",
    "ATVI", "ASTS",
    "BABA", "BIGC", "BIDU", "BILI", "BAC", "BRK-B", "BA", "BNTX", "BEKE",
    "BYND", "BETZ", "BARK",
    "COIN", "CAN", "CRM", "CAKE", "CHWY", "COST", "CLOV", "CPSR", "CRSR",
    "CCL",
    "DBX", "DOCU", "DQ", "DIS", "DAL", "DKNG", "DDOG", "DHI", "DIDI",
    "EBAY", "EH", "ETSY", "ENPH", "ELF", "EDU",
    "F", "FB", "FCX", "FUTU", "FSLY", "FVRR", "FCEL", "FI", "FLYW", "FSLR",
    "GOOG", "GME", "GOCO", "GM", "GOTU",
    "HD", "HOME", "HOFV", "HOOD",
    "IWN", "INTC", "IEA",
    "JPM", "JD", "JKS", "JMIA",
    "KO",
    "LYFT", "LI", "LMND", "LUV", "LITB", "LEN", "LOW", "LULU", "LOGI",
    "MA", "MSFT", "MP", "MMM", "MCD", "MTCH", "MU",
    "NVDA", "NIO", "NET", "NFLX", "NIU", "NEE", "NNDM", "NUE", "NAK", "NKE",
    "OPEN", "OTLY",
    "PYPL", "PLTR", "PINS", "PLUG", "PDD", "PSTG", "PAGS", "PTON", "PAY",
    "PLNHF", "PATH",
    "QQQ",
    "RBLX", "ROKU", "ROOT", "RDNT", "RVLV",
    "SPY", "SQ", "SHOP", "SNOW", "SE", "SKLZ", "SNAP", "SPOT", "SPCE", "SAVE",
    "SPG", "SPLK", "SNPS", "STXB", "SUMO", "STNE", "STPK", "SENS", "SQSP", "SKIN",
    "SAM", "SOFI",
    "T", "TSLA", "TSM", "TWTR", "TWLO", "TDOC", "TWOU", "TLRY", "TREE", "TMUS",
    "TOL", "TAL", "TME", "TALO", "TSN", "TIGR", "TTCF", "TAN", "TCEHY",
    "U", "UBER", "UPWK", "UAL", "UMC", "UEC", "UPST",
    "V", "VIPS",
    "WMT", "WFC", "WTI", "WBA", "WISH",
    "X", "XPEV",
    "YI",
    "ZM", "ZDGE", "ZIP",
]
